In [1]:
import numpy as np

### 1-dimensional array

In [2]:
array_1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array_1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

this is 1 x 11 array

In [4]:
array_1.shape

(11,)

In [5]:
type(array_1)

numpy.ndarray

In [6]:
array_1.size

11

### 2-dimensional array

In [7]:
array_2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

this is 3 x 4 array

In [9]:
array_2.shape

(3, 4)

In [10]:
type(array_2)

numpy.ndarray

In [11]:
array_2.size

12

### Practices

In [12]:
array1 = np.full(6,0)
array2 = np.zeros(6)
array3 = np.full(6, 6)
array4 = np.ones(9)
array5 = np.random.random(6)
array6 = np.random.random(10)

In [13]:
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)
print(array6)

[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]
[6 6 6 6 6 6]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.79298513 0.87608002 0.04528144 0.87616756 0.67042853 0.97841213]
[0.78484697 0.93407599 0.11866046 0.8580596  0.29951547 0.4404399
 0.26798164 0.48082367 0.31262549 0.53475493]


In [14]:
import matplotlib.pyplot as plt

Matplotlib is building the font cache using fc-list. This may take a moment.
